name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sourcebase
        uses: actions/checkout@v2

      - name: Build Operator User Guide
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: 'src/tex/operator-user-guide.tex'
          push: 'no'

      - name: Build FLS Administration Guide
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: 'src/tex/fls-administration-guide.tex'
          push: 'no'

      - name: Promote Generated PDFs
        run: cp ./src/tex/*.pdf ./pdf

      - name: Push PDFs
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'autobuilt documentation update'
          add: '*.pdf'
