name: Latex Compiling

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: LaTeX make
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: 'org.eclipse.passage.operator.docs/user-guide.tex'
          push: 'no'
