# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile-latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile LateX
      uses: vinay0410/tectonic-action@v1.1.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tex_path: 'org.eclipse.passage.operator.docs/user-guide.tex'
        push: 'yes'
